<a href="https://colab.research.google.com/github/Hakimmollik/Hakimmollik/blob/main/Creating_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Creating Tensor

In [ ]:
import torch
print(torch.__version__)

2.11.0+cpu


In [ ]:
if torch.cuda.is_available():
  print("Gpu is available")
  print(f"Device name: {torch.cuda.get_device_name(0)}")

else:
  print("GPU is not avaiable")


GPU is not avaiable


Creating tonsor


In [ ]:
a = torch.empty(2, 3)
a

tensor([[5.5340e-11, 1.1307e+24, 3.2170e+21],
        [1.2944e+22, 4.7465e+27, 2.2231e-10]])

In [ ]:
type(a)

torch.Tensor

In [ ]:
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.rand(2,3)

tensor([[0.2073, 0.8985, 0.4824],
        [0.6523, 0.0078, 0.6125]])

In [ ]:
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
torch.tensor([ [1, 2, 3], [4, 5, 6] ])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
torch.arange(0, 10, 2)

tensor([0, 2, 4, 6, 8])

In [ ]:
torch.linspace(1, 10, 2)

tensor([ 1., 10.])